import { Status } from "../components/Orders/types/orders.types";

export const CHROMADIN: `0x${string}` =
  "0x16a362A10C1f6Bc0565C8fFAd298f1c2761630C5";
export const F3M: `0x${string}` = "0xB15282B59b80C0aACC2609410c910B1Ab0460070";
export const INFURA_GATEWAY_INTERNAL: string =
  "https://f3manifesto.xyz/api/infura/";
export const INFURA_GATEWAY: string = "https://thedial.infura-ipfs.io";
export const GROVE_GATEWAY: string = "https://api.grove.storage/";
export const LOCALES: string[] = ["en", "es", "ar", "ym"];

export const LANGUAGE: { [key in string]: string } = {
  ["en"]: "en",
  ["es"]: "es",
  ["ع"]: "ar",
  ["ŋ"]: "ym",
};

export const IPFS_REGEX: RegExp = /\b(Qm[1-9A-Za-z]{44}|ba[A-Za-z2-7]{57})\b/;
export const F3M_OPEN_ACTION: `0x${string}` =
  "0xBe8FBd070bD469bd486794C5f6a8C7D1DB2FcDc1";
export const DIGITALAX_ADDRESS: `0x${string}` =
  "0xAA3e5ee4fdC831e5274FE7836c95D670dC2502e6";
export const ACCEPTED_TOKENS: string[][] = [
  [
    "QmYCDxCv7mJyjn49n84kP6d3ADgGp422ukKzRyd2ZcGEsW",
    "WGHO",

    "0x6bDc36E20D267Ff0dd6097799f82e78907105e2F",
  ],
  [
    "QmZSDyGYYy9hn8RAUC1vZeZXC5y2H3YimzajJRngCTu5Fq",
    "MONA",
    "0x28547B5b6B405A1444A17694AC84aa2d6A03b3Bd",
  ],
];

export const BOARD_IMAGES: string[] = [
  "QmZkDxAytc1em4HjDugaADBLQ29ke3FSrrrnThas41DzE8",
  "Qmdti74BE3vrCsjFbaR8dcuoLqA9QYjFUHg5rJFKQYjDyW",
  "QmahxsFpuw13Yr33BYaouvf3uhUHq14dec5HPgShoLrbu6",
  "QmU8xZxDhes5c6QVzieRjdTCwQDn8CQZNpLvxSziwV1RLT",
  "QmavSEvTBV4PjohZAz6DkAHFHCG2dMDbt2iVZGzCpNv313",
  "QmToXdYPDtkWEsgmhHKef5yXPuuXKpvmSwGKdfE8u5z5LR",
  "QmY1w74Fp9sJ3sRrUBwELJUFJsnpQroNKbYemU3pdUU8QQ",
  "QmaqTRqYrhKvQeWDEHX9NFZS1w8ZxGPDLC1hYmuCmojDnA",
  "QmdHxY7hbqwwUQHaUUhaGGspCa4JZXtm6SEmz5Q2XietQf",
  "QmavRQgQJ7DpiBEx6TA9iMqM6eswW72bHN4iRfHbymg3tA",
  "QmUH5KCaZR3Sexx9YSSRta6rFsbhVDEuFsQnGsaM9DNnHN",
  "QmahxsFpuw13Yr33BYaouvf3uhUHq14dec5HPgShoLrbu6",
  "QmXBi2ex9QJYUzGZaWvuD1y44xYmDnSNXNfxfvbKhAppD5",
  "QmacyphkA9JZKd7TvhCmmQj5rLiU1T1uhbx6A7WbdTjrwM",
  "QmVmL7MELU5o4DUWhrLs5fW6H9cvBhdt4GwWNqpn9iBnpP",
  "QmcDB1a5aqFppPfZvh16rTsXP7dvjdFwUkRqXte69zaHgY",
  "QmYkWVXHDbNSxBSfUbTUX5nzPgpXD3fmVPz8NjV2C3moHx",
  "QmRMG3apByYx2qwLfqMNnLKLaEia87a5qghpG6agpiy2Tr",
  "QmX54Rdf5hqjX4pbsUDESYpXqz4zp2n9PDAJyEGQk6brzk",
  "QmUVL7BRGpbZUMKsmKxshwzS88d6FgssLpvoiUda7NqPwr",
  "QmX6Ep6TFPWdfq2RiRYxXKJiVUGcDuQ3YxM2GchoFR71bd",
  "QmVcxMp3zainDc87jSZWxL6LZz4H8zcz733CDFWkoA5kGC",
  "QmfVLPL7WG3QrgJ63bK33uzG5RCAntB734vo8J2JBGSYyr",
  "QmfW7kcX3jv9uD3kfhZDidxuPSrRDgfVmdAtHRhbQtSizE",
  "QmebQ98BepuhihKMKgH6qv1XztAW2WoVxeaj13aNUh6dCw",
  "QmRpdtjbpGGPtqma8U4Bmz8k2sXp3vj3sphQbZdS2WFBaP",
  "QmWPRaKEPK8pexCPkdPg5viome8x5RQx8xjRehXkxMY4BH",
  "QmexdPsD4NLMccKny1dciqwiMopJKG2MmLibojozJ6RK2r",
  "QmctyzRkHN2LJ8hrFaMrwqDBgHHUF18WdrcLgMF4BqtBUe",
  "QmRgqssivj2WTMBnfqa5VkRBZSmYtt2JWZ2jqeYjB8pH7U",
  "QmSmXa7BgJComJmvFRexRqegyo8XETZzj6m2JjBkewXXLo",
  "QmQ9x9pZysAe1DLvEVqJJDxVBDJfCCMdhU3Gzafha1T9Z7",
  "QmWPRaKEPK8pexCPkdPg5viome8x5RQx8xjRehXkxMY4BH",
];

export const MARQUEE_IMAGES: string[] = [
  "QmSpAEvvmncSdFgksWikcNt4uYxmD7g7op3Yoq9PgPKMWC",
  "Qme8vMm6zfkXVctNLZh9zUdH7UYy8B27dnhr2YC6uvPL5H",
  "QmPbun9L5he9sC5PQRubbjyxbsG7AAcYFfVgbLR3eRCybC",
  "QmW3f3J9bMf3C1Qoh9V5kfXHYSscMivt4xyXzwGacQkrht",
  "Qmc2od1UCGKczWWmCTFx8DFpjXrdysrhugEdtHPbg6Synq",
  "QmVyej68mhdBbXqStcygmbigHYLUCQHVw7kQAWnFKs9kho",
  "QmbgGwV6vUpMxtL26w3br3UJx2t4tzw5yL3DL14zV7RjSV",
  "QmSL5vDoimgYtBtEadAuSbbpfoAmoyD74odtzs1LFNNMg1",
  "QmYqbX8gNkWBoauWJCyBqo6JD6tmK2JsJzM3fmRaEf2GxC",
  "QmYKGL47zbGqbiipdS3W8tNxbPLa7Qbdwgk4wM2jrsKaZ2",
  "QmY5911kd9hUoJyPJiiooVShdbXk8UV6P7gAEds9SjWq5h",
  "QmeBPwPQEZ7ETkPETUsnX7xArfCH8WTbK3cPgMmq1nv6at",
  "QmUWjSNbknKdnsQtekYkXgdZvXzqQZSkuvNeWKzJngFBHn",
  "QmXPQSEGqcW4aPFZakbjZadmmAvAZ9ecrZMdJ5CQpyx3ah",
  "QmZwbm3DY7gKnrEX8e17n5N9MYexUqhqPLk6jfeacRbohk",
  "QmPo3ScRPcMGKKMJCKnk3stdXwVyvN2RJiDunwmbajrj2D",
  "QmP2ZZsbGanCjbAFVC58y36nVEndfDoP7LENrED1Z1pQoU",
  "QmfBjRYBFHcUHY5WzoHWX6cZP4Fw21p79EbT3cVVkRTQkU",
  "QmP2ZZsbGanCjbAFVC58y36nVEndfDoP7LENrED1Z1pQoU",
  "QmUiERxhe8dVEocNouyhKSYi9GSt4DdairR3rfWPGBhCJC",
  "QmSpAEvvmncSdFgksWikcNt4uYxmD7g7op3Yoq9PgPKMWC",
  "QmVyej68mhdBbXqStcygmbigHYLUCQHVw7kQAWnFKs9kho",
  "QmbgGwV6vUpMxtL26w3br3UJx2t4tzw5yL3DL14zV7RjSV",
  "QmdtU33FTK1nmsUYW1iWFG3ciHZq55jdPi5zb6zUhHURUC",
  "QmRF1ae8FVRsdQVneqydtXrgpVchJEaiYBn1ydXRFg42rT",
  "QmeTAqn6L59xmRtD7ZKGVuDzS23B3UvYJ2oj3mH51UcPKG",
  "QmWgn7f56SzJSSKcLuTTFj8FgBWHNeQPEwgkLkBzDmwnu4",
  "QmThXdUrEGu2RnmTMRUC7o4AEQvEMx5bJGeSCbvrfnq45R",
  "QmbLcV81vukDgUb1RRk5wndmWkpZyu9eZukEhgfRWrUxXS",
  "QmTEVMaauThwVq8NZD7oXJPGGPm5w47ZC5i2dXCNo2sgXi",
  "QmYKGL47zbGqbiipdS3W8tNxbPLa7Qbdwgk4wM2jrsKaZ2",
  "QmPo3ScRPcMGKKMJCKnk3stdXwVyvN2RJiDunwmbajrj2D",
  "QmNeX9SfEpxy8CEKc9sz8ezG4GL4HFwQe8FSGY5rYbwmcJ",
  "QmXEYb1NJWx988xdotU74PDPMWFPTb8rBv2PYDusp4GTdF",
  "QmXzJRJe6ZabKdDN63euBgrePVRMhNeHXAk6SfC9uVmZbo",
  "QmUKSxtvRxvQFrrCdT94qb94PPmm7arvF6kbArvioEWyy1",
  "QmPWLAXYvtAFJXeSumhEj3EzdRwb2xjYUvHmFPyR1ejDki",
  "QmYfj3sW4ztNkragTXcJzX1DJtUjj6U3RqVBSkAybgdnHg",
  "QmQKqHTTEH51FHs5vXxHmdkZDp7oSmGsfb6eshuyTQKQK3",
  "QmR711GNLhMV6cUnQ8stJuqV29TMhGQSqevPZ4toCoYc2N",
  "QmVmbM4TYSREZppbkZ8YAzXuUHCTKr7VWWJu9UjHLiccqK",
  "QmSmJoPmZWGRVsXQAvTJfkUH8kB9rZKZEFnAWN1xjPKLXP",
  "QmcMBbwnjytJuySyLrHj7Zf5p4KJaSpAUDz2YKCmCsUUsv",
  "QmcsDBggaiScuNWCcHJK9eksg1X4Edm85z65ppgv8PSRvm",
  "QmPRMRuoCiS7VzdUVNDFk8KhwjvBSmSCLSpoAb2S47b31R",
  "Qmap2Ti5g3me1iQMACwb4qqjJYMCRqtV1kQQ9TVoQscKoM",
  "QmbXKuZ5nSrXsnojuSPtBABLWXYa2VuQhP29vGKxhYPG9y",
  "Qmcwq7kzWLd2tLzPmvEuHSE6ubG7Pi9mbw2aYSyC1sg2g4",
  "QmaL1vCxU7GHqTcs7eL4xSS5dwBhs4eceVPf3rGfn6wphu",
  "QmXJibjQPgtZk8R4FmCRYd7dcbLkd2BkaxvLq9quY1yynj",
  "Qma11Vwn7Lzb26faiBhiQkkC5UDxC2pujg8LQgwp5J7qhR",
  "QmSJcXqmS63qnHXC47kJtj91cAZkV92b4pDZ2W8hJ35Vnv",
  "QmNmCfABKCpqjkDq2iuFwNYMcZdY8ihWSCJw67Ss6S14Ag",
  "Qma4zWy3ynGjiCDiAheY3JvLgqZdqgGrQ7k4rtLJ5DJajL",
  "QmT58dcrK9e4iNabNr9r4z1HohJKcDVX9kH1eQVFTiVnJe",
  "Qmej1BMpLDmXVGhbyvmd6jCnFdSmU8dtQACzDx82ct64D4",
  "QmSPuvRKfwNvmVwufHHpkStULSA5oXCbh5fStErUCUzc5u",
  "QmTtHDysQtuK9SRzwQA6iD6YYmqDPfw97q48T6xrEheqHJ",
  "QmXWBpn3xuJfEEznsLU8s5ZFeMfh8wqH44EC53rtwexELu",
  "Qmd9zZTVuc1ZjFLoJb7DFYU8BMvXGbC6z8HGtaZm5ALv4G",
  "Qmb7Nfsio4cWX48QjXXZQGtVwtT5H3SSKN3eCp8W1p7VZV",
  "QmayX1iJ4SFHC7Dc55K8MB9SCCBR5CDjGQwfdLDw5rym9b",
  "Qmc5iPKMVAXHVJ255USERmKjxe22d1yJ3MYRCJqJXyYc4g",
  "Qmd2TFqmoZVBzSzkH6KKoq4TueQERCRkMqkcush3vffJVJ",
  "QmYRetZwWFnSvRm43dngNUTfkovU8dCxpB5xaj4tWto6Ci",
  "QmNb4PsxKpatjtyzeScEg8WF2qL33X6Q3uqodfN7kVvVJt",
  "QmSkcLcrcrbZKMzkpmxkN1QmzJpPkWWxU6V6pMfDqS4NHg",
  "QmcrZA6FPB6SskQjRWMVCNYQnATMKZiHtGdbdLwAryXs3S",
  "QmNXkBDtKV25wScdxTqwvgT3GcUPHnQLb3XZ85aQuWjGxA",
  "QmZCi5rKoJCFPe1HupatmCPsNLKBtiiLXtizHnx2w8w8A1",
  "QmXze68kuD9VP3u7pXBxrj7NbV2td3jEVCzF5mxWmyTzLu",
  "QmdHwyuXr1WReAUaKNutG2TyxLuBNDmY1LQQ7RhxUrf9NQ",
  "QmcgNRB6CjCWVDxXEig1PpjPYiFMUip2Y88t6zFnkFNCVe",
  "QmZTFQsnyXejSkyGrFTZm8J32JcZKs2btaZddeo7n3QmCE",
  "Qme8uowSGSx3uU3BLxiiZMHasiQv7veywiWYGi8eQUoBmQ",
  "Qmcnj6oJRJMUPNEJvdVPiLfFXctDKsNT8EPiNbMMpRk6NS",
  "QmYwCMdsedbZ3SRtCCEqUYBJn2Lcdf2vABQhm7ScxUoUHd",
  "QmNvDugwUQ6BQTdSD6AXGNJBmomUxibxG7dKz1QTCtqK9D",
  "QmP1f9jSctxnRKwMaLP3LKFo23VQFoxjemrnjhAmNaaGZN",
  "QmWon4BEPF5b3mDfg9rSRs1sWsr2QbXweXDRvGPmTeh2kT",
  "QmWX3kETxRsW7Vx3yM9M7Sq7Uqg8Pz7ysymyYz1UmTJna4",
  "QmRKuE4MUo9dHS7GDzdpUky7SmtvsgR4Cc9TL2jkGeUm6r",
  "QmQurcZ2NSyVEasPEQ4YjyYJa89rPhLxeCArYNUugnSpBD",
  "QmX92wybeKHqqgL9jHgfwVMwvUHnwgHTwgkvSxcgzCHweh",
  "QmVjyPqXCaBF37fAj7BQQwjGx9FEtXW3B4E11NxHPDvVob",
  "QmVFBj9iJGjTxtz471x8NncDdt4rJpkSmRCevkuLDXZy5F",
  "QmY2d9PnioNiE2JbJCRWdmJAvoEVdNTeKCPXXrpQRxpJhs",
  "Qmc3H4HkmGrPQs845fhDf8WfSc2T86ynCYP7eREXv6fVJg",
  "QmSVHwLmkzvXp68nHv7rbwoYfNj6LxCz7BhmZfDS6pAxWo",
  "QmQh4Dubk6S6hC2KKTdLxj67sepa6ZDin8Qh6HRshgvj2E",
  "QmTYsxh1g9jzGEdGg54B9921jtMwuXJjtyjibtP4h4i5h9",
  "QmVa254PKH4mMVvo8U81F6fej9oWbaX2cSeX3NDAYPKXDV",
  "QmTeyvsFPW7GUkUSPWzrT7kBGLrp6ANPnmE9RmzK5VkGT3",
];

export const FACTORY_RANDOM: string[] = [
  "QmULRoW7Dvp4gMU9vjPyX3UnnNaSddmTCpS9RV3pReoKsi",
  "QmT2qLwMmSSvyh5fxEFfoXTc1RLNQHV2M5gz4neYz4VgGj",
  "QmTtxSPJyE7EbzfVy1ow6qS3oU311W9qVCQDuhvrvEgjNe",
  "QmWWTbbu2jrFopHbqXAs2CKMC3SK6pCT4mzc6Hd5Dkavu4",
  "QmeqCX6m47mXjMnBHvzAHxVWnHFD1CQE27hiTRiRqzqNv4",
  "QmQtt53QUoye1jkWAWcjgf2fMdZ2ChCFYe4wuC9tmvjru8",
  "QmcgD8UxHD1pEnL3Z1RWFDkknScJPSYrPqmXcq1mSwNToj",
  "QmW7RruyDraa6A3iQ6qNCroSxqzWdQEWMM1YY3zEHjCZ5n",
];

export const IDIOMAS: string[] = [
  "English",
  "Spanish",
  "Portuguese",
  "Arabic",
  "Farsi",
  "Hebrew",
  "Yiddish",
  "Japanese",
  "French",
  "Ukranian",
  "Hungarian",
  "Turkish",
  "Yolŋu",
];

export const orderStatus: { [key in number]: Status } = {
  [0]: Status.Fulfilled,
  [1]: Status.Shipped,
  [2]: Status.Shipping,
  [3]: Status.Designing,
};

export const TITLES: string[] = [
  "Printed on-chain, cut offline",
  "This garment doesn’t need a CEO",
  "Assembled at the edge of latency",
  "No atelier, just a node",
  "Manufactured where servers fear to go",
  "One pattern, infinite outputs",
  "Microfactory-born, continent-agnostic",
  "The seamstress is a smart contract",
  "Supply chain burned, not optimized",
  "Textiles without provenance, by design",
  "On-chain textiles with no fashion week invite",
  "The drop happened, you just missed the fork",
  "Styled for zero-permission replication",
  "She wears a mesh network of threads",
  "Wearable factories across the blockspace",
  "No barcodes, no brands, no backend",
  "Seams as sovereign infrastructure",
  "Locally printed, globally uncensored",
  "DAO-designed, human-stitched",
  "Open fabrication > legacy couture",
  "Pattern liberated from label",
  "Drop culture, without platform culture",
  "Woven from burnt IP and broken NDAs",
  "Unlicensed fashion with uptime",
  "The archive can’t contain this output",
  "Textiles are code, and code escaped",
  "Assembly under no jurisdiction",
  "Distribution without discretion",
  "Zero inventory, total intent",
  "Factoryless but fully tooled",
  "Deploying design from cold storage",
  "CC0 textile schematics under public remix",
  "Body-sized protocol executions",
  "Protocols don’t hem, they fork",
  "All nodes agree: fashion is dead",
  "Forged in peer-to-peer pattern sharing",
  "Swapped on-chain, stitched in exile",
  "No POAP, no showroom",
  "Print and flee",
  "Stamped by no nation",
  "Fit-to-fabric, not fit-to-market",
  "Borderless tailoring for unstable futures",
  "SKU-less, trendless, ruthless",
  "Autonomous couture across ungoverned stacks",
  "Minted in silence, worn in noise",
  "Uplinking cloth from basement labs",
  "This isn’t slow fashion. It’s hostile fashion.",
  "Unpackaged, unstable, unforgettable",
  "Deconstructed for transmission",
  "She wore manufacturing like a threat",
  "Each seam negotiates a smart boundary",
  "Tailored at the edge of consensus",
  "Manufactured where latency permits",
  "No logistics, just execution",
  "Woven without apology",
  "Carbonless, cordless, branded by no one",
  "Spec’d for dissidence, not display",
  "Unregulated beauty through hostile firmware",
  "Built for fracture, not flow",
  "No backend, no backenders",
  "Zero-proof manufacturing",
  "Fabrication routed via unstable mesh",
  "Printed from public key entropy",
  "This garment has no release cycle",
  "Precompiled silhouettes",
  "Encrypted fabrication with no fallback",
  "Intended for wear, not resale",
  "Hard-seamed against protocol drift",
  "She assembled herself, off-chain",
  "No sizing tables. Only runtime fits.",
  "Designed in CLI, rendered in cotton",
  "Resistant to logistics",
  "Permanent beta. Irreversible thread.",
  "Runway bypassed. Ledger logged.",
  "No season. No cycle. Just signal.",
  "Patterned by node collisions",
  "Garment born from version conflict",
  "Machine-sewn by distributed intent",
  "Upgraded during transit",
  "She doesn’t shop. She forks.",
  "Resyncing fashion with no central repo",
  "Blueprints with no royalties",
  "Fabricated from undocumented protocol",
  "Testnet uniform, mainnet intention",
  "Coded from scratch in synthetic fiber",
  "Style signed, not supplied",
  "Released under volatile pressure",
  "Sewn in zero trust",
  "Unmodeled and unmoderated",
  "Style rendered at hardware level",
  "Post-industrial, pre-collapse",
  "Apparel designed to fragment",
  "Zipped and executed locally",
  "Asynchronous tailoring for permanent futures",
  "She runs on unstable threads",
  "Fashion without schema or schema migration",
  "Wearable dissent, batch compiled",
  "Failed QC and shipped anyway",
  "Her outfit was a git conflict",
  "Cloth with embedded entropy",
  "Decentralized manufacturing for singular bodies",
  "No front-end, only raw material",
  "Born from textile noise",
  "Her garment speaks in machine tongue",
  "Precompiled anatomy, post-owned fabric",
  "This isn’t a dress — it’s firmware",
  "Threaded for rupture, not runway",
  "Warped beyond standard human fit",
  "Her silhouette escaped architecture",
  "Every seam rejects taxonomy",
  "Tagged by no system, read by no scanner",
  "She wore manufacturing instructions",
  "The garment compiled and walked itself",
  "CC0 fabric with no fixed address",
  "Garment drift under unstable gravity",
  "Body protocol incompatible with legacy fashion",
  "Cut by timestamp, not trend",
  "Built on-body, not off-site",
  "Nothing gendered, everything precise",
  "Anti-archive apparel",
  "Material autonomy in public view",
  "Deformed by sovereign pressure",
  "Run by thread, governed by none",
  "Styled like firmware, updated with intent",
  "Stitched on demand, not desire",
  "Deployable aesthetic artifact",
  "Resides outside regulatory frameworks",
  "Fashioned in encrypted space",
  "She’s not wearing it — it’s wearing her",
  "The pattern was leaked, not drawn",
  "Fully synthetic, fully sovereign",
  "Chassis-compatible couture",
  "No fittings, only injections",
  "Garment = container for unclassifiable presence",
  "Form assembled in null zone",
  "Exoskin for post-authentic bodies",
  "Nothing performative, all executable",
  "She bypassed styling in favor of protocol integrity",
  "Index-resistant tailoring",
  "Anti-signature fashion",
  "Declared incompatible with current frameworks",
  "Patterned from misaligned datasets",
  "The fabric forgot its function",
  "No bias cut, only code bias",
  "Transhuman silhouette with no endpoint",
  "Draped in precompiled gestures",
  "Render artifact worn as uniform",
  "No fashion. Just assertion.",
  "A body shaped by latency",
  "Precision fit for undefined anatomy",
  "Generated not to please, but to fracture",
  "Her look was parsed, and the parser failed",
  "Textiles run on self-governing syntax",
];

export const TITLES_EDIT: { [key in string]: string } = {
  ["old fashioned charm"]: "Old-Fashioned Charm",
  ["pantallas de drive in"]: "Pantallas de Drive-In",
  ["self reconfiguration based on manufacturing needs"]:
    "Self-reconfiguration based on manufacturing needs",
  ["1800 futur synth"]: "1800-FUTUR-SYNTH",
};
